name: User stories
description: Create user stories that will make up features of the app.
title: "[User-Story]: "
labels: ["user-story", "feature"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this user story!
  # As a (user role)
  - type: textarea
    id: user-role
    attributes:
      label: As a...
      description: Describe the user role impacted by this story.
      placeholder: Tell us what your role is.
      value: "user"
    validations:
      required: true
