name: Stories
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
# projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this user story!
  # As a (user role)
  - type: textarea
    id: user-role
    attributes:
      label: As a...
      description: Describe the user role impacted by this story.
      placeholder: Tell us what your role is.
    validations:
      required: true

  # I want (desired outcome)
  - type: textarea
    id: outcome
    attributes:
      label: I want...
      description: Describe the desired outcome the user wants to achieve.
      placeholder: Tell us what you want to see happen.
    validations:
      required: true

  # So that (benefit)
  - type: textarea
    id: benefit
    attributes:
      label: So that...
      description: Explain the benefit or value of achieving the desired outcome.
      placeholder: Tell us the benefitial outcome.
    validations:
      required: true

  # Acceptance criteria (optional)
  - type: textarea
    id: criteria
    attributes:
      label: Acceptance criteria (optional)
      description: List specific conditions that define a successful implementation.
      placeholder: Clear, measurable, and verifiable criteria.
    validations:
      required: false

  # Labels (optional)
  - type: checkboxes
    id: labels
    attributes:
      label: Labels (optional)
      description: Select relevant labels to categorize the story.
      options:
        - label: Bug
          required: true
        - label: Feature
          required: true
        - label: Enhancement
          required: true
        - label: Story
          required: true
        - label: Epic
          required: true
    
  - type: dropdown
    id: version
    attributes:
      label: Priority (optional)
      description: Select the story's urgency based on its impact.
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the app are you currenntly running?
      options:
        - 0.0.1 (Latest)
        - 0.0.0 (Others)
        