name: User stories
description: Create user stories that will make up features of the app.
title: "[User-Story]: "
labels: ["user-story", "feature"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this user story!
  # As a (user role)
  - type: textarea
    id: user-role
    attributes:
      label: As a...
      description: Describe the user role impacted by this story.
      placeholder: Tell us what your role is.
      value: "user"
    validations:
      required: true
  # I want (desired outcome)
  - type: textarea
    id: outcome
    attributes:
      label: I want...
      description: Describe the desired outcome the user wants to achieve.
      placeholder: Tell us what you want to see happen.
      value: "to be notified if my mongocd yaml is wrong"
    validations:
      required: true
  # So that (benefit)
  - type: textarea
    id: benefit
    attributes:
      label: So that...
      description: Explain the benefit or value of achieving the desired outcome.
      placeholder: Tell us the benefitial outcome.
      value: "so that I don't get unexpected errors when I try to weave"
    validations:
      required: true