name: Create Release from Latest Subfolder

on:
  push:
    branches:
      - main

env:
    FOLDER_PATH: templates
    LATEST_TAG: v0.0.1
    LATEST_VERSION: v1alpha1
    RELEASE_README: RELEASE.md
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Folder Exists
        run: |
          ls
          echo "$FOLDER_PATH"
          if [ ! -d "$FOLDER_PATH" ]; then echo "Error: Folder path is not defined"; fi

      - name: Find latest subfolder
        id: get_latest_subfolder
        run: |
          latest_subfolder=$(ls -1 -t $FOLDER_PATH | grep "^d" | head -n1)
          echo "::set-output name=latest_folder::$latest_folder"
          echo "latest_subfolder=$latest_subfolder" >> "$GITHUB_OUTPUT"

      - name: Zip subfolder
        run: |
          cd $FOLDER_PATH
          zip -r "templates_${LATEST_VERSION}.zip" "$FOLDER_PATH/$latest_subfolder/*"

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        # uses: actions/create-release@v1
        with:
          name: mongoprism
          allowUpdates: true
          artifacts: "$FOLDER_PATH/$latest_subfolder.zip"
          tag: $LATEST_TAG
          bodyFile: $RELEASE_README
          draft: true
          makeLatest: true
