name: Release

on:
  push:
    branches:
      # - main
      - none

env:
    TEMPLATE_FOLDER_PATH: templates
    TESTS_PATH: tests
    LATEST_TAG: v0.0.1
    # LATEST_VERSION: v1alpha1
    RELEASE_README: docs/RELEASE.md
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Folder Exists
        shell: bash
        run: |
          ls
          echo "$TEMPLATE_FOLDER_PATH"
          if [ ! -d "$TEMPLATE_FOLDER_PATH" ]; then echo "Error: Folder path is not defined"; fi
