name: Release

on:
  push:
    branches:
      - main

env:
    FOLDER_PATH: tests
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Folder Exists
        shell: bash
        run: |
          if [ ! -d "$FOLDER_PATH" ]; then echo "Error: Folder path ${FOLDER_PATH} is not defined"; fi

      - name: Install and Cache Dependencies
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: '3.12.0'

      - name: Run tests
        run: pipenv run pytest ${FOLDER_PATH}